/**
 * `npm run auth:generate` — regenerates `src/server/db/schema/auth.ts` with the Better Auth CLI
 * (`auth generate --config scripts/auth-cli.ts`), then applies the project conventions:
 *   - `import "server-only"` header (spec §2.2: every src/server file),
 *   - `timestamptz` for every timestamp column (spec §2.5),
 *   - biome formatting.
 * Afterwards run `npm run db:generate` to produce the SQL migration.
 */
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const output = resolve(root, "src/server/db/schema/auth.ts");

function run(cmd: string, args: string[]): void {
  const res = spawnSync(cmd, args, { cwd: root, stdio: "inherit" });
  if (res.status !== 0) {
    console.error(`[auth:generate] ${cmd} ${args.join(" ")} failed`);
    process.exit(res.status ?? 1);
  }
}

run(process.execPath, [
  resolve(root, "node_modules/auth/dist/index.mjs"),
  "generate",
  "--config",
  "scripts/auth-cli.ts",
  "--output",
  output,
  "--yes",
]);

let source = readFileSync(output, "utf8");
source = source.replace(
  /timestamp\("([a-z0-9_]+)"\)/g,
  'timestamp("$1", { withTimezone: true })',
);
const header = [
  'import "server-only";',
  "",
  "// GENERATED by `npm run auth:generate` (Better Auth CLI + project post-processing).",
  "// Do not edit by hand; change src/server/auth/options.ts and regenerate.",
  "",
].join("\n");
if (!source.startsWith('import "server-only"')) source = header + source;
writeFileSync(output, source);

run(process.execPath, [
  resolve(root, "node_modules/@biomejs/biome/bin/biome"),
  "check",
  "--write",
  output,
]);
console.log(`[auth:generate] wrote ${output}`);
