/**
 * `npm run env:init [-- --force]`
 *
 * Writes `.env.local` for local development: freshly generated secrets, local Postgres URLs
 * (geula_dev / geula_test / geula_e2e), mock providers, log email and local storage.
 *
 * Cardcom's *public* test-terminal values are never stored in this repository (spec §7: they live
 * only in `.env.local`, and check-secrets flags the API name). Supply them when running this script:
 *
 *   CARDCOM_TEST_TERMINAL_NUMBER=<terminal> CARDCOM_TEST_API_NAME=<api name> npm run env:init
 *
 * (or `-- --cardcom-terminal=<terminal> --cardcom-api-name=<name>`). They are written to the
 * CARDCOM_* variables, but CARDCOM_MODE stays `disabled` until you opt in.
 *
 * The generated admin password is written to `.env.local` and never printed.
 */
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { userInfo } from "node:os";
import { resolve } from "node:path";

const args = process.argv.slice(2);
const force = args.includes("--force");
const flag = (name: string): string | undefined =>
  args.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3);

const target = resolve(process.cwd(), ".env.local");
if (existsSync(target) && !force) {
  console.log(
    ".env.local already exists; leaving it untouched (pass -- --force to regenerate it).",
  );
  process.exit(0);
}

const secret = (bytes = 32) => randomBytes(bytes).toString("base64url");
const pgUser = encodeURIComponent(userInfo().username);
const dbUrl = (name: string) => `postgres://${pgUser}@localhost:5432/${name}`;

const cardcomTerminal =
  flag("cardcom-terminal") ?? process.env.CARDCOM_TEST_TERMINAL_NUMBER ?? "";
const cardcomApiName =
  flag("cardcom-api-name") ?? process.env.CARDCOM_TEST_API_NAME ?? "";

const lines: string[] = [
  "# Generated by `npm run env:init`. Local development only. NEVER commit this file.",
  "",
  "# Core",
  "APP_ENV=development",
  "APP_URL=http://localhost:3000",
  "# PUBLIC_WEBHOOK_BASE_URL and BETTER_AUTH_URL are derived from APP_URL when unset.",
  `APP_SECRET=${secret()}`,
  `PII_ENCRYPTION_KEY=${randomBytes(32).toString("base64")}`,
  "DEMO_MODE=true",
  "",
  "# Database (Homebrew postgresql@18, trust auth)",
  `DATABASE_URL=${dbUrl("geula_dev")}`,
  `TEST_DATABASE_URL=${dbUrl("geula_test")}`,
  `E2E_DATABASE_URL=${dbUrl("geula_e2e")}`,
  "E2E_PORT=3100",
  "",
  "# Auth (admin:create reads ADMIN_EMAIL / ADMIN_PASSWORD)",
  `BETTER_AUTH_SECRET=${secret()}`,
  "ADMIN_REQUIRE_2FA=false",
  "ADMIN_EMAIL=painter@example.com",
  `ADMIN_PASSWORD=${secret(18)}`,
  "SEED_E2E_USERS=false",
  "",
  "# Abuse controls",
  "RATE_LIMIT_SCALE=1",
  "FORM_MIN_AGE_MS=3000",
  "",
  "# Cron",
  `CRON_SECRET=${secret()}`,
  "",
  "# Payments",
  "PAYMENT_PROVIDERS=mock",
  `MOCK_WEBHOOK_SECRET=${secret()}`,
  "MOCK_PAYMENT_FLOW=direct",
  "",
  "# Cardcom (public test terminal values; enable with CARDCOM_MODE=test and PAYMENT_PROVIDERS=cardcom,mock)",
  "CARDCOM_MODE=disabled",
  "CARDCOM_BASE_URL=https://secure.cardcom.solutions",
  `CARDCOM_TERMINAL_NUMBER=${cardcomTerminal}`,
  `CARDCOM_API_NAME=${cardcomApiName}`,
  "CARDCOM_API_PASSWORD=",
  "CARDCOM_CURRENCIES=ILS",
  "CARDCOM_3DS=Enabled",
  "CARDCOM_WALLETS=",
  "CARDCOM_LATE_WATCH_HOURS=72",
  "CARDCOM_TAIL_DAYS=30",
  "",
  "# PayPal (sandbox credentials from developer.paypal.com)",
  "PAYPAL_MODE=disabled",
  "PAYPAL_CLIENT_ID=",
  "PAYPAL_CLIENT_SECRET=",
  "PAYPAL_WEBHOOK_ID=",
  "PAYPAL_MERCHANT_ID=",
  "",
  "# Tax documents",
  "TAX_DOCUMENTS_MODE=mock",
  "MORNING_MODE=disabled",
  "MORNING_CLIENT_ID=",
  "MORNING_CLIENT_SECRET=",
  "",
  "# Shipping",
  "SHIPPING_CARRIER=mock",
  "DHL_EXPRESS_MODE=disabled",
  "DHL_API_KEY=",
  "DHL_API_SECRET=",
  "DHL_ACCOUNT_NUMBER=",
  "DHL_PAPERLESS_TRADE=false",
  "MOCK_CARRIER_DELIVERY_SECONDS=300",
  "",
  "# Email",
  "EMAIL_DRIVER=log",
  "RESEND_API_KEY=",
  "EMAIL_FROM=Geula Gallery <studio@example.com>",
  "",
  "# Storage",
  "STORAGE_DRIVER=local",
  "LOCAL_STORAGE_DIR=.data/uploads",
  "",
];

writeFileSync(target, lines.join("\n"), { mode: 0o600 });
console.log(
  `Wrote ${target} (secrets generated; admin password stored there, not printed).`,
);
if (!cardcomTerminal || !cardcomApiName) {
  console.log(
    "Cardcom test-terminal values were not supplied; CARDCOM_TERMINAL_NUMBER / CARDCOM_API_NAME are empty (CARDCOM_MODE=disabled).",
  );
}
